# Generated by Django 2.2.5 on 2019-10-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stype',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
