# Generated by Django 2.2.5 on 2019-10-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191020_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
